server:
  port: 8080

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service API
        url: /v3/api-docs/auth-service
      - name: Policy Service API
        url: /v3/api-docs/policy-service

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 404E635HatsuneNMiki82F413F4428472B4B6250645367566B5970

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service-openapi
              uri: lb://auth-service
              predicates:
                - Path=/v3/api-docs/auth-service
              filters:
                - RewritePath=/v3/api-docs/auth-service, /v3/api-docs

            - id: policy-service-openapi
              uri: lb://policy-service
              predicates:
                - Path=/v3/api-docs/policy-service
              filters:
                - RewritePath=/v3/api-docs/policy-service, /v3/api-docs
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              # No auth filter — login/register must be public  

            - id: policy-service
              uri: lb://policy-service
              predicates:
                - Path=/api/policies/**
              filters:
                - Authentication

              #for admin access in policy service
            - id: policy-admin-service
              uri: lb://policy-service
              predicates:
                - Path=/api/admin/policies/**
              filters:
                - Authentication
                - RoleCheck=ROLE_ADMIN

            - id: claims-service
              uri: lb://claims-service
              predicates:
                - Path=/api/claims/**
              filters:
                - Authentication
              # Any authenticated user can access
      
            - id: admin-service
              uri: lb://admin-service
              predicates:
                - Path=/api/admin/**
              filters:
                - Authentication
                - RoleCheck=ROLE_ADMIN
              # Gateway blocks non-admins before request even reaches service