server:
  port: 8085

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
  mail:
    host: smtp.gmail.com
    port: 587
    username: saumyapande05@gmail.com
    password: hpac jotp tmqz flui
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
