server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85