server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
            - id: kyc
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/kyc/**

            - id: auth-docs
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/v3/api-docs/**,/auth/swagger-ui/**,/auth/webjars/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /${segment}
    
            - id: policy
              uri: lb://POLICY-SERVICE
              predicates:
                - Path=/api/policies/**
    
            - id: policy-docs
              uri: lb://POLICY-SERVICE
              predicates:
                - Path=/policy/v3/api-docs/**
              filters:
                - RewritePath=/policy/(?<segment>.*), /${segment}
    
            - id: claims
              uri: lb://CLAIMS-SERVICE
              predicates:
                - Path=/api/claims/**
    
            - id: claims-docs
              uri: lb://CLAIMS-SERVICE
              predicates:
                - Path=/claims/v3/api-docs/**
              filters:
                - RewritePath=/claims/(?<segment>.*), /${segment}
  application:
    name: api-gateway
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Policy Service
        url: /policy/v3/api-docs
      - name: Claims Service
        url: /claims/v3/api-docs

jwt:
  secret: HatsuneMikuagdawififafoawfnwa6767dhawdda
  expiration: 900000