server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///e:/projectideas/Java_Capgemini2025/sdet-Programming/_Sprint_SmartSure/config-repo/
