server:
  port: 8081
  forward-headers-strategy: native     

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/smartsure_auth_db?createDatabaseIfNotExist=true
    username: root
    password: 3141@MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  autoconfigure:
    exclude:
     - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
     - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: HatsuneMikuagdawififafoawfnwa6767dhawdda
  expiration: 900000

springdoc:
  api-docs:
    path: /v3/api-docs                    
  swagger-ui:
    enabled: false                        
  override-with-generic-response: false